### ISSUE TITLE
$sourceDomain

### ISSUE THREAD

**Issue by Macbernie** [npflood/AWS-SNS-HTTP-PHP-ENDPOINT#2]
Hi,
Thanks for your script, but what is the $sourceDomain ? What should I give him ?
I only have $allowedTopic = "arn:aws:sns:us-east-1:437351776702:My-Topic";
Thanks

**Comment by ckrack** [comment]
I suggest using the official Amazon SDK for this:
https://github.com/aws/aws-php-sns-message-validator
